### ISSUE TITLE
Using the data as std::array in Vector class

### ISSUE THREAD

**Issue by Boiethios** [GamedevFramework/gf#1]
Why not doing that ? Then one can use the “smart” `for` to go through the Vector.

I can do it, but I will not spend my time unnecessarily if you prefer C array.

**Comment by jube** [comment]
You mean replacing `T data[N]` with `std::array<T, N>`? Note that you can use the range-based `for` with C arrays. This currently works:

```c++
gf::Vector4i vec(1, 2, 3, 4);

for (int elem : vec.data) {
  // do something with elem
}
```

I can also add `begin()` and `end()` so that this could be possible:

```c++
gf::Vector4i vec(1, 2, 3, 4);

for (int elem : vec) {
  // do something with elem
}
```

**Comment by Boiethios** [comment]
Yes I mean that. I learned something thanks to you, I did not know it was possible to use the range-based `for` with C arrays.

I think the second syntax is the best because it is more intuitive/direct : that will be read “I want the elems from the vec”. I can write the code if you want, that will be quick.

**Comment by jube** [comment]
As you want. Do not forget to read the [contribution guidelines](https://github.com/GamedevFramework/gf/blob/master/CONTRIBUTING.md). In this case, if you add `begin()` and `end()` in `Vector`, you also have to do it in the specializations. And do not forget the documentation ;)

**Comment by jube** [comment]
Is this issue considered closed?

**Comment by Boiethios** [comment]
Yes. I shall see if I can help you on ~~bigger~~ real features, but for now, I have merely no time.
