### ISSUE TITLE
Unable to compile Test/Examples

### ISSUE THREAD

**Issue by RUSshy** [GamedevFramework/gf#10]
Hello

I'm on Arch Linux, GCC 6.3.1, CMAKE 3.7.2

I try to compile Test or Examples and i get the following error:

```make
[100%] Linking CXX executable gf_tests
../library/libgf0.so.0.3.0: undefined reference to `gf::v1::Range<unsigned int>::Iterator::Iterator(unsigned int)'
../library/libgf0.so.0.3.0: undefined reference to `gf::v1::Range<int>::Iterator::Iterator(int)'
../library/libgf0.so.0.3.0: undefined reference to `gf::v1::Range<float>::Iterator::Iterator(float)'
collect2: error: ld returned 1 exit status
make[3]: *** [tests/CMakeFiles/gf_tests.dir/build.make:438: tests/gf_tests] Error 1
make[2]: *** [CMakeFiles/Makefile2:1251: tests/CMakeFiles/gf_tests.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1263: tests/CMakeFiles/gf_tests.dir/rule] Error 2
make: *** [Makefile:539: gf_tests] Error 2

```

**Comment by jube** [comment]
Tried with a Debian sid, GCC 6.3.0, CMake 3.7.2 and got no error. That's weird.

From the error, I would say that the nested `Iterator` class should be generated with the explicit instantiation of the `Range` class but it is not. I can not find if the nested class should also be explicitely instantiated or if it is a compiler bug.

**Comment by RUSshy** [comment]
I'll try with GCC 6.3.0 once i can boot on my linux partition

**Comment by RUSshy** [comment]
I couldn't boot into my arch partition anymore so i removed it and reinstalled Ubuntu and now it works.. i hate Arch xD

But i have another issue; this time on macOS Sierra, i'll open a new ticket

**Comment by jube** [comment]
I tried with a ArchLinux VM with the same versions as yours and it compiles. Weird!

**Comment by romainreignier** [comment]
Just for information, on a recent Arch system with GCC 7.1.1 and CMake 3.8.2, everything (lib, examples, games, tools) build correctly.
So this issue is maybe no more relevant.

**Comment by jube** [comment]
Fine, so I am closing it.
