### ISSUE TITLE
Possibility to draw Texture directly with the SpriteBatch

### ISSUE THREAD

**Issue by jube** [GamedevFramework/gf#12]
Proposed by @RUSshy in #9

**Comment by jube** [comment]
Should be OK but I don't really see a good API. Here are some (not exclusive) proposals:

~~~
void draw(const Texture& texture, const RenderStates &states=RenderStates());
void draw(const Texture& texture, const RectF& textureRect, const RenderStates &states=RenderStates());
void draw(const Texture& texture, const RectF& textureRect, Vector2f position, const RenderStates &states=RenderStates());
~~~

For something more complex, my advice would be to create a Sprite.

**Comment by RUSshy** [comment]
https://github.com/GamedevFramework/gf/blob/master/library/SpriteBatch.cc#L44

I'm not sure if comparing transform is really usefull?
It'll add an useless draw call if i just move a sprite no?

**Comment by jube** [comment]
You are right. I wonder if there is a bug or not. Because normally, the final transform should be identity as every vertex is transformed directly. So the comparison is useless. Investigating that.

**Comment by jube** [comment]
Closing this one too as it has been added in the develop branch.

**Comment by jube** [comment]
After thinking about it, there is no bug. The transform is really part of the render state and I made a mistake because there are two transforms : the one of the render state and the one of the sprite. Conclusion, the comparison is useful.
