### ISSUE TITLE
libGDX Scene2D port

### ISSUE THREAD

**Issue by jube** [GamedevFramework/gf#13]
Proposed by @RUSshy in #9 

See [libGDX wiki on Scene2D](https://github.com/libgdx/libgdx/wiki/Scene2d).

**Comment by jube** [comment]
Porting everything will not be easy as it is tightly linked with the rest of the library. But before your request, I was really interested in the `Action` part. My plan was:

- Add interpolations (easings functions): that part is quite easy and I already have some code for this
- Add `Action` (or rather `Activity` as there already is an `Action` class in gf): that part is more difficult, I thought about it and I could not find a simple enough API, still searching. This part could be an independent API that could be used anywhere.
- Add an `Actor` class? Add a scene graph? I do not really know.

**Comment by RUSshy** [comment]
Yes the Action par is really usefull to make some good and lively UIs, http://crashinvaders.com/ they are actively using it for their UI, and it is really a game changer, and again really easy to use, just like everything libGDX have :p
