### ISSUE TITLE
Framerate limit

### ISSUE THREAD

**Issue by jube** [GamedevFramework/gf#14]
Proposed by @RUSshy in #9

**Comment by jube** [comment]
Would you like something like SFML, i.e. based on some sort of sleep? Would you like the same API as SFML?

**Comment by RUSshy** [comment]
I don't know how it's handled exactly in SFML, but i never had CPU usage issue, and it was easy to use ``window.SetFrameLimit(60)``

**Comment by jube** [comment]
Fine. This will be in the next release.

**Comment by jube** [comment]
It's in the develop branch! I added an example to play with vertical synchonization and framerate limit (and check everything works).

**Comment by RUSshy** [comment]
Awesome thanks :D
