### ISSUE TITLE
[Widgets] Bug with point to

### ISSUE THREAD

**Issue by Xeryko** [GamedevFramework/gf#20]
#18 
WidgetContainer doesn't do the job in the pointTo function on resized window....
Have to handle window resizing in it....

**Comment by jube** [comment]
> Have to handle window resizing in it....

I am not in favor of this solution. We have to find a global solution. Maybe a flaw in the initial design.

**Comment by Xeryko** [comment]
Do we have to let the user handle the window resizing?

**Comment by jube** [comment]
I found a solution, it's in the develop branch. I removed `getGlobalBounds()` and put `contains()` instead which can easily be computed for any `Transformable`. So I close the bug.
