### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by sherjilozair** [GamedevFramework/gf#21]
I really loved the choices made by this library, but it's unfortunate that it doesn't support macos as of now. Any plans on supporting MacOS in the near future?

**Comment by jube** [comment]
macos is not supported because I do not have access to a macos machine. But if someone is willling to add this support, I will gladly accept it.

In the case of your problem, I think it's the same as #11. I will try to investigate and understand what happens but I think it will be difficult without a macos machine.

**Comment by jube** [comment]
I have two questions:

- What is the compiler error you fixed?
- Can you try to replace `SDL_GL_CONTEXT_PROFILE_ES` by `SDL_GL_CONTEXT_PROFILE_CORE` in `library/Library.cc` line 54 and tell me if it changes anything?

**Comment by sherjilozair** [comment]
I printed out the version details, if that's any help to you:

```
glGetString(GL_VENDOR) is ATI Technologies Inc.
glGetString(GL_RENDERER) is AMD Radeon Pro 560 OpenGL Engine
glGetString(GL_VERSION) is 4.1 ATI-1.60.24
glGetString(GL_SHADING_LANGUAGE_VERSION) is 4.10
```

I also checked to make sure that `GL_BLEND` had the correct value, and it did (`0x0BE2 `).

**Comment by sherjilozair** [comment]
Changing 2 to 3 has no effect.

**Comment by sherjilozair** [comment]
Perhaps we can find time to connect over IRC or gitter? Chat would help us iterate faster. I'll be hanging out at #gf-devel today, so if you wanna do this, ping me over there.

**Comment by sherjilozair** [comment]
ES is still being used because of `gladLoadGLES2Loader` being called. I managed to make example 04 work by using `gladLoadGLLoader` and by adding the necessary glad files using http://glad.dav1d.de/. But examples 05 still didn't work. I'd recommend taking a look at [raylib](https://github.com/raysan5/raylib/blob/master/src/rlgl.c) for how it manages to use difference GL versions and platforms.

**Comment by jube** [comment]
From what I can see in raylib:

- they [include system GL headers](https://github.com/raysan5/raylib/blob/master/src/rlgl.c#L97)
- they [do not use glad to load functions](https://github.com/raysan5/raylib/blob/master/src/rlgl.c#L1330)
- they assume that GL 3.3 is used (from Google, it has been here since macOS 10.9)

Do you want to test that? I can create a branch with those changes and push it if you want.

**Comment by sherjilozair** [comment]
I looked at this again. It seems the main issue is that a lot of the OpenGL code you've written assumes a GLES 2.0, but this is not available in macos (unless we use ANGLE). For instance, you don't bind vertex array objects and vertex buffer objects, which is required for the 3.3 core profile.

I managed to make a few more examples work by adding code for the same here: https://github.com/sherjilozair/gf/blob/macos/library/RenderTarget.cc#L317

I think one way to fix this issue going forward would be to use both 3.3 core profile and 2.0 ES profile to test your code in your operating system. If 3.3 core works, then it will also work for mac.

Another way is to use ANGLE, but since this is only a 2D game framework, working with the intersection of 3.3 core and 2.0 ES should be a much easier and feasible route than adding the ANGLE dependency.

What do you think?

**Comment by jube** [comment]
Given that OpenGL 3.3 is needed for macos, I think I will try to include an optional GL 3.3 version in gf. Then, if you are on Windows or Linux, you will have the choice between GL 3.3 and GLES 2.0, and if you are on Mac, you will have GL 3.3 automatically.

The difference between both versions is not that difficult to support. I will try to merge your PR in a separate branch and add some options in `CMakeLists.txt` to handle everything. Is that OK for you?

I have a few questions regarding your PR:

- why do you get the vao in `RenderTarget.cc` before creating the vbo?
- is it normal that you do not delete the vbo at the end of the function?
- is it normal that you do not delete the vao in the `Window` destructor?

**Comment by sherjilozair** [comment]
Awesome. It would be great if GF could support OpenGL 3.3.

Please don't consider my pull request ready-to-merge. It was created just to share my attempts with you, and was written in a very hacky way to get things running. The lessons are more important than the code, which is that GL 3.3 requires VAOs and VBOs to be binded. There were a few other lessons as well, if you see the Texture.cc changes in my PR. But since I don't really know the architecture of GF very well, I think it would be better if you do the changes yourself rather than accepting my PR. Like you noticed, I don't take proper care of deleting the objects after using them.

**Comment by jube** [comment]
I just pushed a series of commit in develop with support for OpenGL 3.3 (and a few bug fixes found during that development). You really did a great job with this bug, and I took inspiration from your PR. I hope everything will work correctly.

**Comment by sherjilozair** [comment]
Unfortunately, this didn't work for me. I get segfaults in pretty much all the examples. Did you test with GL 3.3 core profile at your end? If you did, this discrepancy may be due to macs being stricter than windows on what counts as correct opengl code.

I also had to replace all instances of <SDL.h> to <SDL2/SDL.h>, to make it compile. Otherwise <SDL.h> would find my SDL 1 headers.

I also added #include <cstddef> to DataObject.h to make it compile.

**Comment by jube** [comment]
Damn!

> Did you test with GL 3.3 core profile at your end?

Yes, I tested everything and fixed all the errors. All the examples work for me. My main system is Linux. But I also have a Windows machine to test (but unfortunately, I have some connectivity problems these days and I can not pull from github).

> Running examples/05_triangle, I get a segfault in the call to glGenBuffers in VertexBuffer.cc around line 85.

The only segfault that can occur here is that glGenBuffers is a null pointer. I really wonder if using OpenGL directly is the right way. Do you get any message in the console (you may need to activate the GF_DEBUG option in cmake)?

> I also had to replace all instances of <SDL.h> to <SDL2/SDL.h>, to make it compile. Otherwise <SDL.h> would find my SDL 1 headers.

The preferred way to include SDL headers is to *not* include the SDL2 directory. cmake uses FindSDL2 which is in the cmake directory in the source tree. It may have a bug which finds SDL1 headers instead of SDL2 headers.

> I also added #include <cstddef> to DataObject.h to make it compile.

I already pushed it in the latest commit.

**Comment by sherjilozair** [comment]
Yes, `glGenBuffers` is 0, basically due to `glad.h` being imported in `VertexBuffer.cc` instead of `priv/OpenGLFwd.h`. I fixed it, and now the examples work. Awesome work @jube! Could you make the change at your end? I don't want to send a patch with the SDL2 changes. I'll try to figure out the SDL2 issue now.

**Comment by sherjilozair** [comment]
So the SDL thing is only an issue if I have both SDL1 and SDL2 installed. Then it does pick SDL1 instead of SDL2. If I uninstall SDL1, then it compiles properly.

**Comment by sherjilozair** [comment]
I sent a PR for this glad fix and the cstddef fix. Do you know if it's possible to setup a CI system to also check for macos?

**Comment by jube** [comment]
> Yes, glGenBuffers is 0, basically due to glad.h being imported in VertexBuffer.cc instead of priv/OpenGLFwd.h.

My fault. I did a `grep` but forgot to remove this one...

> Do you know if it's possible to setup a CI system to also check for macos?

I think Travis-CI can make macos builds. I will try to put that in place. I will open another issue.
