### ISSUE TITLE
Adding Outline to RectangleShape removes texture

### ISSUE THREAD

**Issue by yousifyaqeen** [GamedevFramework/gf#23]
is it normal that when i add setOutlineThickness to a RectangleShape object with a texture the texture is not displayed and the texture is replaced by white background ?
this should work according to the  [documentation](http://gamedevframework.github.io/v0.8.0/classgf_1_1_shape.html#a47e97612eccde5930d2bd5e4569ff5c4) , but it's possible i misunderstood the document
 
here is my code : 
```
gf::Texture testTexture;
  if (!testTexture.loadFromFile("testTexture.png")) {
    return -1;
  }

gf::RectangleShape tile;

tile.setSize({ 75.0f, 75.0f });
tile.setOutlineColor(gf::Color::Blue);
tile.setOutlineThickness(2);
tile.setPosition({10 + (tile.getSize().width + 2), 10 + (tile.getSize().height + 2) });
tile.setTexture(testTexture);

}
```

**Comment by jube** [comment]
The bug is confirmed. I try to fix it.

**Comment by jube** [comment]
Fixed ;)
