### ISSUE TITLE
Rendering Problem with SquareGrid Class

### ISSUE THREAD

**Issue by yousifyaqeen** [GamedevFramework/gf#28]
when using the SquareGrid Class when the window is resized the grid is shown twice , if you continue resizing the window the issue is more visible.

this is the code that i used 
```
#include <gf/Event.h>
  #include <gf/RenderWindow.h>
  #include <gf/Window.h>
  #include <gf/Grid.h>
  int main() {
    gf::Window window("GFBattleship", { 500, 500});
    gf::RenderWindow renderer(window);
    gf::SquareGrid  test(gf::Vector2u(50,50),gf::Vector2f(10.0f,10.0f) , gf::Color::White ,1.0f);
    while (window.isOpen()) {
      gf::Event event;
      while (window.pollEvent(event)) {
        switch (event.type) {
                 case gf::EventType::Closed:
                 window.close();
                 break;
               }
    }
    renderer.draw(test);
    renderer.display();
  }
    return 0;
  }

```
**when the window starts**
![error1](https://user-images.githubusercontent.com/6253469/45385327-c2478880-b610-11e8-80d2-e9bd4fac9097.png)

**resized**

![error2](https://user-images.githubusercontent.com/6253469/45385326-c2478880-b610-11e8-92c5-80504d79643e.png)

![error3](https://user-images.githubusercontent.com/6253469/45385325-c2478880-b610-11e8-9255-b34277210023.png)

**Comment by jube** [comment]
You forgot the call to `renderer.clear()` before drawing anything ;)

**Comment by yousifyaqeen** [comment]
i was just updating the issue , it took me a  while to realize it :)
