### ISSUE TITLE
sprite.png missing in examples

### ISSUE THREAD

**Issue by Popolon** [GamedevFramework/gf#3]
First thanks a lot for your nice game framework!
I looked a lot for a 'multimedia' framework that work on OpenGL ES. Most functions seems here for base of development :).

I tried all the examples,  and the last one has a missing sprite.png file. This file isn't in the source tree either.

 cd /usr/local/share/doc/GF/examples
./99_index
[1471371209][Debug][Graphics] Shader loaded from file: '/usr/local/share/gf/shaders/default.vert'
[1471371209][Debug][Graphics] Shader loaded from file: '/usr/local/share/gf/shaders/default.frag'
[1471371209][Debug][Graphics] Shader loaded from file: '/usr/local/share/gf/shaders/default.vert'
[1471371209][Debug][Graphics] Shader loaded from file: '/usr/local/share/gf/shaders/default_alpha.frag'
[1471371209][Warn][Graphics] Could not load image from file 'sprite.png': can't fopen

**Comment by jube** [comment]
Thanks! As for the example, there is no sprite.png. This example is special, it is the example from the  [documentation index](http://gamedevframework.github.io/v0.1.0/). It's just here to verify that it compiles. So I think this bug is not really a bug.

Do you think there is a need for sprite.png? In that case, there is also a need for DroidSans.ttf (or any other .ttf).

**Comment by Popolon** [comment]
Ok, I just tough that was something forgot. perhaps reusing 12_bomb.png and 16_DejaVuSans.ttf should be less strange for people during first test, and to visualize what examples done.

**Comment by Popolon** [comment]
A sizeof on a std::size_t variable is 4 bytes long on my ARMv7h system.

**Comment by jube** [comment]
Maybe an explicit comment at the beginning of the file stating that the file can compile but cannot be run?

**Comment by jube** [comment]
I put a little text in the comment. I hope this will be enough. If it's not, I will move this file outside the example repository.
