### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by sb-baifeng-sb** [GamedevFramework/gf#34]
Texture.h

line 339
class GF_API Texture : public BareTexture {
};

line 67
class GF_API BareTexture {
  public:
    BareTexture(Format format);
    ~BareTexture();
};

Texture's parent class is BareTexture, but the destructor of BareTexture is not virtual

**Comment by jube** [comment]
There is no need for a virtual destructor for various reasons:

- You always use either an `AlphaTexture` or a `Texture` directly, in this case the right destructor is called
- I do not see any use case where you would only have a pointer on a `BareTexture` and want to delete it
- Even if this last weird case would happen, there is no data in `AlphaTexture` and in `Texture` i.e. there is nothing to destroy in children classes so there is no risk of memory leak

See [this discussion](https://softwareengineering.stackexchange.com/questions/284561/when-not-to-use-virtual-destructors) for more arguments.

I could prevent the problematic use case by making the destructor of `BareTexture` protected. Would that be a solution for you?

**Comment by sb-baifeng-sb** [comment]
thank's your answer, I think I know what's going on.
