### ISSUE TITLE
gf::BasicText not updating correctly his local bounds

### ISSUE THREAD

**Issue by NiiRoZz** [GamedevFramework/gf#42]
Hello,

gf::BasicText not updating correctly his local bounds, when using alignment.

```
gf::TextWidget basicText("Hellooooooooo ? test", m_Font);
basicText.setDefaultTextColor(gf::Color4f(1,1,1,1));
basicText.setPosition({150.f, 100.f});
basicText.setAlignment(gf::Alignment::Center);
std::cout << basicText.getLocalBounds().getWidth() << " " << basicText.getLocalBounds().getHeight() << std::endl;

target.draw( basicText, states);
```

When you are executing this code in a render function, you will be able to see the getWidth() function not returning a correct value, in this case 0.
But if you use setParagraphWidth and set his value to 1.
You will be able to see the getWidth() return 1.

![Bug_gf::BasicText](https://user-images.githubusercontent.com/8999198/73451996-3e0eb600-4369-11ea-9ba2-6d6651527ea3.png)

Sounds like width is calculated from paragraph width instead with letter.
Paragraph width calculation is correct when the paragraph width > letter width.

**Comment by jube** [comment]
Yes width is calculated from paragraphWidth because, generally, paragraphWidth is wide enough to hold the text. I need it to handle properly the case when the text do not fill the paragraphWidth. What I can do is compute width with paragraphWidth only if paragraphWidth is > 0.

**Comment by jube** [comment]
The fix is in the develop branch.

**Comment by NiiRoZz** [comment]
Fix is working fine.

I'm closing the issue.
