### ISSUE TITLE
Cmake generating only x64 build for windows on develop branch

### ISSUE THREAD

**Issue by NiiRoZz** [GamedevFramework/gf#49]
Hello,

When generated files with Cmake, he generated only a configuration for x64 on windows.

My version : Windows 10 and Cmake 3.17.0-rc3 and Visual Studio 2019

If it's should be like that, maybe update the documentation for windows and use `.\vcpkg install sdl2:x64-windows freetype:x64-windows boost:x64-windows zlib:x64-windows` instead `.\vcpkg install sdl2 freetype boost zlib` because vcpkg only install x86 packages if not defining it.

**Comment by jube** [comment]
Right. That's what I do in Appveyor!
