### ISSUE TITLE
SDL completion

### ISSUE THREAD

**Issue by Xeryko** [GamedevFramework/gf#5]
Hi!
I think that a little function like `Keyboard::getKeyFromName()` would be nice :)

**Comment by jube** [comment]
Yes, it should be quite easy. I will add `getKeycodeFromName()` and `getScancodeFromName()`. Would you need another API in this area?

**Comment by Xeryko** [comment]
For now i'm good and I don't think i'll need another API.

**Comment by jube** [comment]
Pushed in the `develop` branch. Will be in the next release.
