### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by Xeryko** [GamedevFramework/gf#6]
Trying to assign a grey color to a font seems not workinig.
I only have a white or a black color result.

**Comment by jube** [comment]
Investigating this weird bug...

**Comment by jube** [comment]
I cannot reproduce your bug. I created a test case in `tests/bugs/bug6.cc` (in the `develop` branch) and it displays a gray text as expected. Could you give me a piece of code that does not work?

**Comment by Xeryko** [comment]
This is my function to store a Color in a gf::Color4u :
`m_mainMenuLabel.setColor(gf::Color::Grey(0.5f));`

and this is my function to render the final text on screen :
```
void Label::render(gf::RenderTarget &target) {
    gf::Text text(m_text, m_font, m_characterSize);
    text.setPosition(m_position);
    text.setColor(m_color);
    target.draw(text);
}
```

**Comment by Xeryko** [comment]
I found that using `gf::Color::Grey()` with a `gf::Color4u` isn't working.

**Comment by jube** [comment]
Your bug is here. You should use `gf::Color4f` and not `gf::Color4u`. When you assign a gray color to a `gf::Color4u`, there is an implicit conversion from `float` to `uint8_t` which results in 0.5f being 1 (or 0). And then, when you use it in `setColor`, there is another conversion from `uint8_t` to `float` so 1.0f (or 0.0f) which results in white or black.

**Comment by Xeryko** [comment]
So to store a Grey value in a gf::Color4u, values should looks like `{ 150, 150, 150, 255}` ?

**Comment by jube** [comment]
Use a `gf::Color4f`, that's the simplest way to do. Otherwise, you can use `gf::Color::rgba()` and `gf::Color::convert()` (in the `develop` branch, the names are ugly and may change in the future) to convert from one format to another.

**Comment by Xeryko** [comment]
Okay okay, anyway, i wanted to switch to gf::Color4f, looks like a way more simplier.
