### ISSUE TITLE
Build is broken.

### ISSUE THREAD

**Issue by ruslanzelinskyy** [GamedevFramework/gf#63]
Project can't be build:

CMake Error happens after cd build, cmake ../ -DGF_BUILD_GAMES=ON -DGF_BUILD_TOOLS=ON
Could not find SDL2 include directory

Ubuntu 20.04 (WSL)

**Comment by jube** [comment]
Have you installed the `libsdl2-dev` package? Anyway, beware that WSL does not work with gf, some people have tried but no one has been able to open a window. SDL2 can not initialize an OpenGL context.

**Comment by ruslanzelinskyy** [comment]
My bad - missed to install libraries.
I've successfully initialized a opengl windows with raylib on wsl.
But now when running any example i've error about assets is missing.
Binary path should be configured and assets should be in the same dir with binary.
So when i've moved assets dir (gf/examples/assets) to binaries dir (gf/build/examples/assets)
It worked!
https://prnt.sc/1105v7j

**Comment by jube** [comment]
Nice!

For the `assets` directory, if you install it (with `make install` for example), everything will be installed in the same directory so that the assets will be found when executing any example.
