### ISSUE TITLE
Workflow questions

### ISSUE THREAD

**Issue by MetalMaxMX** [GamedevFramework/gf#69]
Hello! I've read about this project following a comment on an user from the FastTracker II repo (an issue from it). And there was something curious that I wanted to know about this project in particular.

See, the project advertises itself as "It is not a [game engine](https://en.wikipedia.org/wiki/Game_engine), it is more something like a framework, similar to [libGDX](https://libgdx.badlogicgames.com/) in the Java world." and that is something that I am curious about, because LibGDX, by virtue of its Java heritage, can cross-compile and export on a variety of platforms from a single host/PC to many other OSes or devices. And this is where I am going with this. 

What's the official way to release binaries from multiple OSes with this? Could one install something like MinGW on a Linux box and be able to cross-compile and build for Windows? I've noticed from this link (https://gamedevframework.github.io/v1.2.0/build_and_install.html) on the docs that Linux requires GCC or Clang while Windows requires MSVC. No mention of MinGW (be it from MSYS on Windows or from Linux itself) 

Lastly. What's the scripting language support for this framework? Or are you meant to work natively with what the examples give? (so, C++) 

Cheers!
MetalMaxMX

**Comment by jube** [comment]
Hello ! We have never tested to build gf with MinGW or MSYS. It should work more or less, as these are GCC-based compiler. And I think all the dependencies compiles with these two (especially SDL2).

As for the scripting language, it is planned for v2 of the library (with many other breaking changes). It has no release date at the moment. But for v1, no scripting language support.

**Comment by MetalMaxMX** [comment]
Hi! Thanks for answering my queries, I do know that SDL2 does compiles to other platforms through MinGW so this project probably can as well, awesome. 

Out of curiosity, what is the scripting language planned for v2? I imagine Lua due to its portability, or maybe Squirrel?

**Comment by jube** [comment]
I am still hesitating. It will be either Python (because it is very widespread) or a home-made scripting language.

**Comment by MetalMaxMX** [comment]
I think the idea of a home-made scripting language makes more sense since it'll be custom-tailored for the framework  itself while Python is more generic and all so is harder to tame in some scenarios. Just my 2 cents though. 

Feel free to close the issue now, as you got my current questions solved now. Good luck with v2 and the choice of scripting language!
