### ISSUE TITLE
THANKS!

### ISSUE THREAD

**Issue by RUSshy** [GamedevFramework/gf#9]
I just love this library, it feels like libGDX wich is awesome, keep up the good work, i'm a fan, thanks a lot :D :D :D

**Comment by jube** [comment]
You are welcome. Do not hesitate to ask for features that are not yet present in the library.

**Comment by RUSshy** [comment]
For the moment there are just 2 things that i would love to see

* Being able to draw Texture directly with the SpriteBatch
* Screen management, with transition, i have something working already, once cleaned i'll send a PR
* libGDX Scene2D port, but this is going to be huge effort, i'll have to make my own UI, so i'll try to port it then share it with you

**Comment by RUSshy** [comment]
Oh and also frameLimit to avoid high CPU usage, on my mac even with VSYNC enabled it takes full CPU usage for 1 core

**Comment by jube** [comment]
I added some new issues for these requests. I did not really understand what you mean by "screen management with transition" so I left it, I will wait for your PR.
